# Stage 1
# Build docker image of react app
FROM node:18-alpine3.16 as build
WORKDIR /nestjs
COPY package*.json ./
COPY tsconfig.json ./
# install and cache app dependencies
RUN yarn install

# Copy 
COPY . .
# RUN npx prisma generate
EXPOSE 3000
CMD ["yarn", "start:dev"]
#CMD ["yarn", "start"]