@hostname = http://localhost:3000
@Authorization = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbiIsInBhc3N3b3JkSGFzaCI6IiQyYiQxMCRYcDhoSnRBL2k2T0JobS9YOG0uTjJlSlZ6LlB6ejVDQklHN281c0VRREYwRHI1QnlUaHpaMiIsImF1dGhLZXkiOiI1Mjc0NWI2Ny1lNTQ2LTQ4ODItOWE5Zi0yOTM0OTA5YmIzMWUiLCJjb25maXJtZWRBdCI6MTYwMDY2MjE2MCwiYmxvY2tlZEF0IjpudWxsLCJyZWdpc3RyYXRpb25JcCI6bnVsbCwiY3JlYXRlZEF0IjoxNjgzOTI0OTk3LCJ1cGRhdGVkQXQiOjE2OTc2NjI3MjguNTc4LCJmbGFnIjoxMCwibGFzdExvZ2luQXQiOjE2OTQ1NDQ5MzAsIm9yaWdpbiI6IjE2ODM1NTQ4MTEiLCJudW1UdXJtYSI6MSwibmFtZSI6IkFkbWluIiwiYmlvIjpudWxsLCJ3aGF0c2FwcCI6IjM0OTg0MjkzNTE5IiwiY3BmIjoiMDE2MDU3NDM2NjYiLCJwb3N0YWxDb2RlIjoiMzg0MDA0MjgiLCJhZGRyZXNzIjoiUnVhIFPDo28gTG91cmVuw6dvIiwiYWRkcmVzc051bWJlciI6IjYyMSIsImFkZHJlc3NEaXN0cmljdCI6Ik9zdmFsZG8gUmV6ZW5kZSIsImltYWdlIjpudWxsLCJjaXR5SWQiOjIzODksInN0YXRlSWQiOjExLCJyb2xlcyI6ImFkbWluIiwiaWF0IjoxNjk4MzUwMjI5LCJleHAiOjE2OTg5NTUwMjl9.FJ-jw6CWis44sf2ar5EXeg2kIg-arkv3VLnXurcdMwo

### Login
POST {{hostname}}/auth/login
Content-Type: application/json

{
    //"email":"c.dj@hotmail.com",
    "email":"admin",
    "password": "1234"
}

### Get Profile (Logged User)
GET {{hostname}}/auth/profile
Authorization: {{Authorization}}

### Get Lists
GET {{hostname}}/lead/lists
Authorization: {{Authorization}}

### Get Leads
GET {{hostname}}/lead/all/1/10
Authorization: {{Authorization}}

### Get City by id
GET {{hostname}}/lead/id/45
Authorization: {{Authorization}}

### Get City by id
GET {{hostname}}/lead/search/car
Authorization: {{Authorization}}

### Get City by id
GET {{hostname}}/lead/list/preconexao
Authorization: {{Authorization}}

### Get City by id
GET {{hostname}}/lead/load/preconexao/carlitosceo@gmail.com
Authorization: {{Authorization}}

### Get City by id
GET {{hostname}}/lead/confirm/preconexao/carlitosceo@gmail.com
Authorization: {{Authorization}}

### Get City by id
GET {{hostname}}/lead/notdisturb/preconexao/carlitosceo@gmail.com
Authorization: {{Authorization}}

### Create city
POST {{hostname}}/lead
Authorization: {{Authorization}}
Content-Type: application/json

{
    "confirm": 0,
    "email": "carlitosceo+121212@gmail.com",
    "list": "preconexao",
    "name": "Carlos Defelícibus Junior",
    "naoperturbe":0,
    "origin":"default",
    "whatsapp": ""
}

### Update city
PATCH {{hostname}}/lead/45
Authorization: {{Authorization}}
Content-Type: application/json

{
    "name": "TEstexxx"
}

### Delete city
DELETE {{hostname}}/lead/45
Authorization: {{Authorization}}