@hostname = http://localhost:3000
@Authorization = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJjYXJsaXRvc2Nlb0BnbWFpbC5jb20iLCJwYXNzd29yZF9oYXNoIjoiJDJiJDEwJFpnZjBSLkROZzRIbENDekI4c1JibnVENFgxUzE5djU5YVZiM1dXNFNaMFQ4SnhyZjFkUVhXIiwiYXV0aF9rZXkiOiI1Mjc0NWI2Ny1lNTQ2LTQ4ODItOWE5Zi0yOTM0OTA5YmIzMWUiLCJjb25maXJtZWRfYXQiOjE2MDA2NjIxNjAsImJsb2NrZWRfYXQiOm51bGwsInJlZ2lzdHJhdGlvbl9pcCI6bnVsbCwiY3JlYXRlZF9hdCI6MTY4MzkyNDk5NywidXBkYXRlZF9hdCI6MTY4NzM2NzE4MSwiZmxhZyI6bnVsbCwibGFzdF9sb2dpbl9hdCI6MTY5NDU0NDkzMCwib3JpZ2luIjoiMTY4MzU1NDgxMSIsIm51bV90dXJtYSI6MSwibmFtZSI6IkFkbWluIiwiYmlvIjpudWxsLCJ3aGF0c2FwcCI6bnVsbCwiY3BmIjpudWxsLCJwb3N0YWxDb2RlIjpudWxsLCJhZGRyZXNzIjpudWxsLCJhZGRyZXNzTnVtYmVyIjpudWxsLCJhZGRyZXNzRGlzdHJpY3QiOm51bGwsImltYWdlIjpudWxsLCJjaXR5X2lkIjpudWxsLCJzdGF0ZV9pZCI6bnVsbCwicm9sZXMiOiJhZG1pbiIsImlhdCI6MTY5NzIwOTcwNiwiZXhwIjoxNjk3ODE0NTA2fQ.KLbjDL1feiFs9IvDgW_2E6HmPk3sCYxrYq-yguy9BJ8

### Login
POST {{hostname}}/auth/login
Content-Type: application/json

{
    //"email":"c.dj@hotmail.com",
    "email":"carlitosceo@gmail.com",
    "password": "1234"
}

### Get Profile (Logged User)
GET {{hostname}}/auth/profile
Authorization: {{Authorization}}

#######################################

###
GET {{hostname}}/massmail/all/1/10
Authorization: {{Authorization}}

###
GET {{hostname}}/massmail/list/Testando/1/10
Authorization: {{Authorization}}

###
GET {{hostname}}/massmail/id/1
Authorization: {{Authorization}}

### Create leademail
POST {{hostname}}/massmail
Authorization: {{Authorization}}
Content-Type: application/json

{
    "list": "captacao",
    "subject": "Opa tudo bem?",
    "message": "Estou testando. Espero que esteja tudo ok.",
    "quantity": 27,
    //"created_at": "27",
    "status": 1
}

### Update leademail
PATCH {{hostname}}/massmail/1
Authorization: {{Authorization}}
Content-Type: application/json

{
    "message": "TEstexxx",
    "list": "Testando"
}

### Delete leademail
DELETE {{hostname}}/massmail/1
Authorization: {{Authorization}}