name: CARLITOS CI
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Repositorio
        uses: actions/checkout@v1

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          #node-version: '16.x' //TROQUEI
          node-version: '20.x' 
      - run: rm -rf package-lock.json
      - run: rm -rf yarn.lock

      - run: npm install
      - run: npm run build

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          #TARGET: ${{ secrets.REMOTE_TARGET }}
          TARGET: /www/wwwroot/nodeapps/api_carlosdj/

      - name: Post Deploy
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.REMOTE_HOST }}
            username: ${{ secrets.REMOTE_USER }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            port: ${{ secrets.REMOTE_PORT }}
            script: | 
              cd /www/wwwroot/nodeapps/api_carlosdj/
              yarn
              yarn pm2:restart
      
      # - run: npm run restart

      # - run: |
      #     export PATH=$PATH:/root/.nvm/versions/node/v16.20.1/bin
      #     pm2 list

      # - run: npm install pm2@latest -g #install pm2 global
      # - run: pm2 -V #check pm2 version
      # - run: pm2 list #check pm2 list
      # #running pm2 in mode cluster and --watch set to auto restart if index.js have changes.
      # - run: pm2 start dist/src/main.js --name apimodelo  #--watch -i max
      # # - name: pm2 restart
      # #   run: |
      # #     ssh ${{ vars.EC2_USERNAME }}@${{ vars.EC2_HOST }} -p ${{ vars.EC2_HOST_PORT }} '
      # #       export PATH=$PATH:/home/ubuntu/.nvm/versions/node/v18.13.0/bin;
      # #       pm2 restart apimodelo --update-env
      # #     '